# Generated by Django 4.0.4 on 2022-09-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nascimento', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=25)),
                ('local', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=4)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=20)),
                ('obs', models.TextField()),
                ('especie', models.CharField(max_length=20)),
                ('raca', models.CharField(max_length=20)),
                ('porte', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
