# Generated by Django 4.0.4 on 2022-09-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lifepet', '0002_cadastro_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='teste',
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='especie',
            field=models.CharField(choices=[('cachorro', 'Cachorro'), ('gato', 'Gato')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='porte',
            field=models.CharField(choices=[('grande', 'Grande'), ('medio', 'Medio'), ('pequeno', 'Pequeno')], max_length=10),
        ),
    ]
